/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2320;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class DLinkedSeqTest {
    private DLinkedSeq<Integer> seq;

  @BeforeEach void makeDLinkedSeq() {
    seq = new DLinkedSeq<>();
  }

  @Test void emptyOnCreate() {
    assertEquals(0, seq.size());
  }
}
